name: 'Terra-Master packing action'
description: 'Generate your own tpk for your Terra-Master Nas'
author: "Yunkun Huang"

inputs:
  folder-name: 
    description: 'your source code folder'
    required: true
    default: '.'
  arch: 
    description: 'your nas arch. use x86_apps or arm_apps'
    required: false
    default: 'x86_apps'
  tpk-name: 
    description: 'your tpk name'
    required: false
    default: 'demo'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.folder-name }}
    - ${{ inputs.arch }}
    - ${{ inputs.tpk-name }}