name: test

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: htynkn/terra-master-packing-action@master
        with:
          folder-name: test/
      - name: "Check tpk existence"
        uses: andstor/file-existence-action@v1
        with:
          files: "demo_TOS_APP_1.0.0_x86_64.tpk"
